openapi: 3.1.0
info:
  version: 1.0.0
  title: Pepita.com
  termsOfService: '#'
  contact:
    email: edson.belem@inmetrics.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://github.com/edsonbelemjr/teste/blob/main/assets/logo.png?raw=true'
  description:
    $ref: ./info-description.md
tags:
  - name: Pepita
    description: Esta api corresponde ao processo Pepita.
  - name: User
    description: Operações sobre os usuários.
  - name: Tag
    description: Essa é a tag de descrição
servers:
  - url: 'http://example.com/api/v1'
  - url: 'https://example.com/api/v1'
paths:
  '/users/{username}':
    $ref: 'paths/users@{username}.yaml'
  /pepita:
    $ref: paths/pepita.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
components:
  # Autenticação
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
